/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaoCaoRouteImport } from './routes/bao-cao'
import { Route as DatPhongRouteImport } from './routes/dat-phong'
import { Route as DonRouteImport } from './routes/don'
import { Route as LichRouteImport } from './routes/lich'
import { Route as PhongRouteImport } from './routes/phong'
import { Route as ThietKeRouteImport } from './routes/thiet-ke'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoRoute = BaoCaoRouteImport.update({
  id: '/bao-cao',
  path: '/bao-cao',
  getParentRoute: () => rootRouteImport,
} as any)
const DatPhongRoute = DatPhongRouteImport.update({
  id: '/dat-phong',
  path: '/dat-phong',
  getParentRoute: () => rootRouteImport,
} as any)
const DonRoute = DonRouteImport.update({
  id: '/don',
  path: '/don',
  getParentRoute: () => rootRouteImport,
} as any)
const LichRoute = LichRouteImport.update({
  id: '/lich',
  path: '/lich',
  getParentRoute: () => rootRouteImport,
} as any)
const PhongRoute = PhongRouteImport.update({
  id: '/phong',
  path: '/phong',
  getParentRoute: () => rootRouteImport,
} as any)
const ThietKeRoute = ThietKeRouteImport.update({
  id: '/thiet-ke',
  path: '/thiet-ke',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRoute
  '/dat-phong': typeof DatPhongRoute
  '/don': typeof DonRoute
  '/lich': typeof LichRoute
  '/phong': typeof PhongRoute
  '/thiet-ke': typeof ThietKeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRoute
  '/dat-phong': typeof DatPhongRoute
  '/don': typeof DonRoute
  '/lich': typeof LichRoute
  '/phong': typeof PhongRoute
  '/thiet-ke': typeof ThietKeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRoute
  '/dat-phong': typeof DatPhongRoute
  '/don': typeof DonRoute
  '/lich': typeof LichRoute
  '/phong': typeof PhongRoute
  '/thiet-ke': typeof ThietKeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bao-cao' | '/dat-phong' | '/don' | '/lich' | '/phong' | '/thiet-ke'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/bao-cao' | '/dat-phong' | '/don' | '/lich' | '/phong' | '/thiet-ke'
  id:
    | '__root__'
    | '/'
    | '/bao-cao'
    | '/dat-phong'
    | '/don'
    | '/lich'
    | '/phong'
    | '/thiet-ke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoCaoRoute: typeof BaoCaoRoute
  DatPhongRoute: typeof DatPhongRoute
  DonRoute: typeof DonRoute
  LichRoute: typeof LichRoute
  PhongRoute: typeof PhongRoute
  ThietKeRoute: typeof ThietKeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao': {
      id: '/bao-cao'
      path: '/bao-cao'
      fullPath: '/bao-cao'
      preLoaderRoute: typeof BaoCaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dat-phong': {
      id: '/dat-phong'
      path: '/dat-phong'
      fullPath: '/dat-phong'
      preLoaderRoute: typeof DatPhongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don': {
      id: '/don'
      path: '/don'
      fullPath: '/don'
      preLoaderRoute: typeof DonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich': {
      id: '/lich'
      path: '/lich'
      fullPath: '/lich'
      preLoaderRoute: typeof LichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phong': {
      id: '/phong'
      path: '/phong'
      fullPath: '/phong'
      preLoaderRoute: typeof PhongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thiet-ke': {
      id: '/thiet-ke'
      path: '/thiet-ke'
      fullPath: '/thiet-ke'
      preLoaderRoute: typeof ThietKeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoCaoRoute: BaoCaoRoute,
  DatPhongRoute: DatPhongRoute,
  DonRoute: DonRoute,
  LichRoute: LichRoute,
  PhongRoute: PhongRoute,
  ThietKeRoute: ThietKeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
